### ISSUE TITLE
x264 doesn't support normal profils like baseline, main & high

### ISSUE THREAD

**Issue by ocrete** [UnitedRPMs/x264#2]
You're building it with a bit-depth of 10, so it will only support high bit depths formats!

**Comment by kuboosoft** [comment]
@ocrete  Don't worry; is only feature; but I will make the standar compatibility ;)
Is very strange Do you you tested it? because the current x264 provides the standard compatibility but also the 10 bit changes in other directory...

**Comment by ocrete** [comment]
I see that someone just added ifs for the 10bit support.. In practice, you need to install the 10bit library somewhere else or with another soname than the normal one. x264 bulids only in one mode at a time, and the 10bit one is mostly useless. So you need to build it twice and create two separate binaries to have both 8-bit and 10-bit support.

**Comment by kuboosoft** [comment]
@ocrete I made a x264-10 bit but only for test... I am reverting to 8-bit; also checking if we need a massive rebuild...

**Comment by paulcarroty** [comment]
@ocrete @kuboosoft Let's test the latest build with 8bit - https://github.com/UnitedRPMs/travis-rpm-builder/releases
